### ISSUE TITLE
Turbo-carto: Unhandled promise rejection

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1000]
Running the tests with master (node9):
```
$ ./node_modules/.bin/_mocha -c -u tdd -t 5000 test/acceptance/multilayer_server.js --grep "fails if CartoCSS is bogus"


  tests from old api translated to multilayer
(node:7055) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'css' of undefined
    at /home/raul/dev/public/Windshaft-cartodb/node_modules/turbo-carto/src/turbo-carto.js:22:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:7055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ layergroup creation fails if CartoCSS is bogus (143ms)


  1 passing (208ms)
```

@enekid I think this started happening with the update for https://github.com/CartoDB/turbo-carto/pull/79. Can you have a look or should I assign this to RT?

**Comment by Algunenano** [comment]
I can confirm that switching the order of the .catch and .then in getCartoCss was indeed the culprit. Reverting that change removes the error (but it might break other stuff).

**Comment by dgaubert** [comment]
@enekid, Is that fixed already?

**Comment by enekid** [comment]
It should be (I've switched the order of the .then() .catch() calls). @Algunenano, can you please run the tests with node9?

**Comment by Algunenano** [comment]
I can confirm it's gone. 
```
$ ./node_modules/.bin/_mocha -c -u tdd -t 5000 test/acceptance/multilayer_server.js --grep "fails if CartoCSS is bogus"

  tests from old api translated to multilayer
    ✓ layergroup creation fails if CartoCSS is bogus (154ms)


  1 passing (228ms)
```

Thanks a lot.
