### ISSUE TITLE
Broken listing features tests

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1079]
Running the tests with PG11 + Postgis 3 + PROJ 5.2/6.0 I get this:

```$ ./node_modules/.bin/_mocha -c -u tdd -t 5000 --exit test/acceptance/cluster.js


  cluster
    w/o aggregation
      ✓ should return error while fetching disaggregated features (289ms)
      ✓ with aggregation disabled should return error while fetching disaggregated features (85ms)
    fetch features within a cluster grid
      ✓ should get features for z: 0 cartodb_id: 1, res: 0.5 (55ms)
      ✓ should get features for z: 0 cartodb_id: 2, res: 0.5 (51ms)
      ✓ should get features for z: 0 cartodb_id: 3, res: 0.5 (42ms)
      ✓ should get features for z: 0 cartodb_id: 4, res: 0.5 (43ms)
      ✓ should get features for z: 0 cartodb_id: 5, res: 0.5 (50ms)
      ✓ should get features for z: 0 cartodb_id: 6, res: 0.5 (49ms)
      ✓ should get features for z: 0 cartodb_id: 7, res: 0.5 (52ms)
      ✓ should get features for z: 0 cartodb_id: 1, res: 1 (46ms)
(node:5300) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
      ✓ should get features for z: 0 cartodb_id: 2, res: 1 (49ms)
      ✓ should get features for z: 0 cartodb_id: 3, res: 1 (54ms)
      ✓ should get features for z: 0 cartodb_id: 4, res: 1 (43ms)
      ✓ should get features for z: 0 cartodb_id: 5, res: 1 (47ms)
      ✓ should get features for z: 0 cartodb_id: 6, res: 1 (50ms)
      ✓ should get features for z: 0 cartodb_id: 7, res: 1 (49ms)
      ✓ should get features for z: 0 cartodb_id: 1, res: 50 (42ms)
      1) should get features for z: 0 cartodb_id: 5, res: 50
      2) "after each" hook for "should get features for z: 0 cartodb_id: 5, res: 50"


  17 passing (1s)
  2 failing

  1) cluster
       fetch features within a cluster grid
         should get features for z: 0 cartodb_id: 5, res: 50:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped

  [
-   {
-     cartodb_id: 4,
-     type: 'even',
-     value: 0
-   },
    {
...
    }
  ]
      + expected - actual

       [
         {
      -    "cartodb_id": 4
      -    "type": "even"
      -    "value": 0
      -  }
      -  {
           "cartodb_id": 5
           "type": "odd"
           "value": 1
         }
      
      at testClient.getClusterFeatures (test/acceptance/cluster.js:320:28)
      at Function.finish (test/support/test-client.js:723:20)
      at next (node_modules/step/lib/step.js:51:23)
      at /home/raul/dev/public/Windshaft-cartodb/test/support/test-client.js:714:21
      at Server.<anonymous> (test/support/assert.js:122:24)
      at emitCloseNT (net.js:1616:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  2) "after each" hook for "should get features for z: 0 cartodb_id: 5, res: 50":

      AssertionError [ERR_ASSERTION]: uncaughtException:

AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped

  [
-   {
-     cartodb_id: 4,
-     type: 'even',
-     value: 0
-   },
    {
...
    }
  ]
    at testClient.getClusterFeatures (test/acceptance/cluster.js:320:28)
    at Function.finish (test/support/test-client.js:723:20)
    at next (node_modules/step/lib/step.js:51:23)
    at /home/raul/dev/public/Windshaft-cartodb/test/support/test-client.js:714:21
    at Server.<anonymous> (test/support/assert.js:122:24)
    at emitCloseNT (net.js:1616:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (test/support/test_helper.js:89:12)
```

**Comment by dgaubert** [comment]
I'm going to force a specific order in the query to avoid this kind of errors.

**Comment by dgaubert** [comment]
I thought it was related to the default order but seems more related to a change in the behavior of `ST_Intersects` or `ST_MakeEnvelope` in PostGIS 3. Does that make sense to you @Algunenano?

**Comment by Algunenano** [comment]
> I thought it was related to the default order but seems more related to a change in the behavior of ST_Intersects or ST_MakeEnvelope in PostGIS 3. Does that make sense to you @Algunenano?

Nope, the behaviour hasn't change. If I had to, I'd bet on PROJ precision improvements but I can't say for sure.

It can also be reproduced with production packages for [PG11](https://launchpad.net/~cartodb/+archive/ubuntu/postgresql-11).

**Comment by dgaubert** [comment]
> I'd bet on PROJ precision improvements

Ok! The controversial point is placed in (0, 0) which makes sense with your theory. I can move this point a little bit to avoid failing tests. Let me know if you have a better idea.

**Comment by Algunenano** [comment]
> I can move this point a little bit to avoid failing tests. Let me know if you have a better idea.

LGTM
