### ISSUE TITLE
Fatal exit on ENOMEM

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1116]
```
[2019-07-31 18:16:07.666] [FATAL] [default] - Error
    at process.exitProcessFn (/home/ubuntu/www/node-windshaft/releases/20190730102543/app.js:249:60)
    at process.emit (events.js:189:13)
    at Object.create (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder.js:22:33)
    at createResource (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:269:13)
    at ensureMinimum (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:304:9)
    at Object.me.destroy (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:161:5
)
    at Timeout.removeIdle [as _onTimeout] (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/gene
ric-pool.js:188:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
Error
    at process.exitProcessFn (/home/ubuntu/www/node-windshaft/releases/20190730102543/app.js:249:60)
    at process.emit (events.js:189:13)
    at Object.create (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder.js:22:33)
    at createResource (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:269:13)
    at ensureMinimum (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:304:9)
    at Object.me.destroy (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:161:5
)
    at Timeout.removeIdle [as _onTimeout] (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/grainstore/node_modules/generic-pool/lib/gene
ric-pool.js:188:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
```

The handler is using logging.fatal for signals that aren't SIGINT or SIGTERM, so when a children sent the ENOMEM signal the tiler abruptly stopped instead of using the shutdown() procedure.

cc/  @CartoDB/rt-managers

**Comment by Algunenano** [comment]
Closing stale ticket
