### ISSUE TITLE
Uncaught exception: Range filter expect to have at least one value in greater_than, greater_than_or_equal, less_than, less_than_or_equal, min, or max numeric params

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1117]
```
[2019-08-05 00:25:38.777] [FATAL] [default] - Error: Range filter expect to have at least one value in greater_than, greater_than_or_equal, less_than, less_than_or_equal, min, or max numeric params
    at new Range (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/range.js:25:15)
    at createFilter (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:40:12)
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:14:20
    at Array.map (<anonymous>)
    at Object.QueryBuilder$getSql [as getSql] (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:12:10)
    at BaseNode.Node.getQuery (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/node/node.js:144:25)
    at BaseNode.AggregateIntersection.sql (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/node/nodes/aggregate-intersection.js:61:34)
    at NodeSqlAdapter.createTableQuery (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/postgresql/node-sql-adapter.js:24:31)
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/service/database.js:113:49
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/service/database.js:93:16
Error: Range filter expect to have at least one value in greater_than, greater_than_or_equal, less_than, less_than_or_equal, min, or max numeric params
    at new Range (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/range.js:25:15)
    at createFilter (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:40:12)
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:14:20
    at Array.map (<anonymous>)
    at Object.QueryBuilder$getSql [as getSql] (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/filter/query-builder.js:12:10)
    at BaseNode.Node.getQuery (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/node/node.js:144:25)
    at BaseNode.AggregateIntersection.sql (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/node/nodes/aggregate-intersection.js:61:34)
    at NodeSqlAdapter.createTableQuery (/home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/postgresql/node-sql-adapter.js:24:31)
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/service/database.js:113:49
    at /home/ubuntu/www/node-windshaft/releases/20190730102543/node_modules/camshaft/lib/service/database.js:93:16
[2019-08-05 00:25:38.778] [INFO] [default] - Process is going to exit with code: 1
[2019-08-05 00:26:23.778] [INFO] [default] - Process didn't close on time. Force exit
```

Killed 2 servers tonight.

cc/ @CartoDB/rt-managers

**Comment by dgaubert** [comment]
Just a bit of context, the exception is totally legit. We should handle it properly and respond with the error to the client, `HTTP: 400` instead of crashing the process shamefully.

The problem is [here](https://github.com/CartoDB/camshaft/blob/3cae41a41d4a3c037389c6f02630919197476f37/lib/service/database.js#L113): `sqlWrappedNode.createTableQuery()` is throwing a sync error in a callback method which is not being caught correctly before callback with error.

**Comment by dgaubert** [comment]
It happened again on `2019-08-31 12:23:27`. 😞

**Comment by jgoizueta** [comment]
I'll fix it in camshaft: https://github.com/CartoDB/camshaft/issues/397
Then it'll be a question of updating the camshaft dependency.
