### ISSUE TITLE
Module missing: Windshaft

### ISSUE THREAD

**Issue by Thijs-Velde** [CartoDB/Windshaft-cartodb#295]
Hi,

After running git cloning and npm installing, I attempt to run node app.js, but on boot I get the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/thijsiee/cartodb/Windshaft-cartodb/app.ks'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Currently I am using node version 0.10.26  on Ubuntu 12.04.5 LTS.

**Comment by rochoa** [comment]
Hi,

What do you get if you try to just install the `windshaft` module?

```shell
~/path-to/windshaft-cartodb $ npm install windshaft
```

**Comment by Thijs-Velde** [comment]
Odd, that worked wonders, cheers
