### ISSUE TITLE
Failing acceptance tests

### ISSUE THREAD

**Issue by pnorman** [CartoDB/Windshaft-cartodb#352]
`make test-acceptance` gives

```
  58 passing (3s)
  1 pending
  3 failing

  1) render limits with onTileErrorStrategy layergroup creation and tile requests works even if they are slow but returns fallback:
     Uncaught Error: ENOENT, no such file or directory '/Windshaft-cartodb/test/results/png/image-test-1451592539599.png'
      at Object.fs.unlinkSync (fs.js:765:18)
      at /Windshaft-cartodb/test/support/assert.js:31:12
      at /Windshaft-cartodb/test/support/assert.js:63:13
      at ChildProcess.exithandler (child_process.js:641:7)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:743:16)
      at Socket.<anonymous> (child_process.js:956:11)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Pipe.close (net.js:466:12)

  2) multilayer:postgres=layergroup_url=/api/v1/map layergroup with 2 layers, each with its style:
     Uncaught Error: ENOENT, no such file or directory '/Windshaft-cartodb/test/results/png/image-test-1451592539873.png'
      at Object.fs.unlinkSync (fs.js:765:18)
      at /Windshaft-cartodb/test/support/assert.js:31:12
      at /Windshaft-cartodb/test/support/assert.js:63:13
      at ChildProcess.exithandler (child_process.js:641:7)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:743:16)
      at Socket.<anonymous> (child_process.js:956:11)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Pipe.close (net.js:466:12)

  3)  "after each" hook:
     Uncaught AssertionError: Unexpected keys found in redis: [db=0]map_cfg|4e97ea7db1db42da52b0867f780f53c6, [db=5]user:localhost:mapviews:global
      at taskDone (/Windshaft-cartodb/test/support/test_helper.js:99:20)
      at /Windshaft-cartodb/test/support/test_helper.js:109:24
      at try_callback (/Windshaft-cartodb/node_modules/redis/index.js:579:9)
      at RedisClient.return_reply (/Windshaft-cartodb/node_modules/redis/index.js:664:13)
      at ReplyParser.<anonymous> (/Windshaft-cartodb/node_modules/redis/index.js:312:14)
      at ReplyParser.EventEmitter.emit (events.js:95:17)
      at ReplyParser.send_reply (/Windshaft-cartodb/node_modules/redis/lib/parser/javascript.js:300:10)
      at ReplyParser.execute (/Windshaft-cartodb/node_modules/redis/lib/parser/javascript.js:211:22)
      at RedisClient.on_data (/Windshaft-cartodb/node_modules/redis/index.js:535:27)
      at Socket.<anonymous> (/Windshaft-cartodb/node_modules/redis/index.js:91:14)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)



./run_tests.sh: line 133:   160 Segmentation fault      (core dumped) mocha -u tdd -t 5000 ${TESTS}
# Stats
total_connections_received:567
total_commands_processed:1652
instantaneous_ops_per_sec:160
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:386
keyspace_misses:139
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
# Keyspace
db0:keys=3,expires=1,avg_ttl=7199802
db5:keys=4,expires=0,avg_ttl=0
Killing test redis pid 85
Dropping PostgreSQL test database isn't implemented yet

```

**Comment by dgaubert** [comment]
This is why test is trying to remove a temporal image what is not previously generated. Maybe that image is not generated due to an environmental issue (file descriptors, some kind of race condition).

Are you running test for `master` branch?. I've got green always, I had to increase file descriptor limit: `ulimit -n 2056`.

Hope this helps.

**Comment by pnorman** [comment]
I tried it, didn't change anything. `ulimit -n` was telling me that the default limit is 524288.

I'm now getting different errors:

```
    1) layergroup with 2 layers, each with its style
    2) "after each" hook

  0 passing (145ms)
  2 failing

  1) multilayer:postgres=layergroup_url=/api/v1/map layergroup with 2 layers, each with its style:
     Uncaught Error: ENOENT, no such file or directory '/Windshaft-cartodb/test/results/png/image-test-1451924392539.png'
      at Object.fs.unlinkSync (fs.js:765:18)
      at /Windshaft-cartodb/test/support/assert.js:31:12
      at /Windshaft-cartodb/test/support/assert.js:63:13
      at ChildProcess.exithandler (child_process.js:641:7)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:743:16)
      at Socket.<anonymous> (child_process.js:956:11)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Pipe.close (net.js:466:12)

  2)  "after each" hook:
     Uncaught AssertionError: Unexpected keys found in redis: [db=0]map_cfg|4e97ea7db1db42da52b0867f780f53c6, [db=5]user:localhost:mapviews:global
      at taskDone (/Windshaft-cartodb/test/support/test_helper.js:99:20)
      at /Windshaft-cartodb/test/support/test_helper.js:109:24
      at try_callback (/Windshaft-cartodb/node_modules/redis/index.js:579:9)
      at RedisClient.return_reply (/Windshaft-cartodb/node_modules/redis/index.js:664:13)
      at ReplyParser.<anonymous> (/Windshaft-cartodb/node_modules/redis/index.js:312:14)
      at ReplyParser.EventEmitter.emit (events.js:95:17)
      at ReplyParser.send_reply (/Windshaft-cartodb/node_modules/redis/lib/parser/javascript.js:300:10)
      at ReplyParser.execute (/Windshaft-cartodb/node_modules/redis/lib/parser/javascript.js:211:22)
      at RedisClient.on_data (/Windshaft-cartodb/node_modules/redis/index.js:535:27)
      at Socket.<anonymous> (/Windshaft-cartodb/node_modules/redis/index.js:91:14)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)
```

**Comment by dgaubert** [comment]
And have you installed ImageMagick (http://www.imagemagick.org)?.

**Comment by pnorman** [comment]
Ah, that was it.

Now I get

```

  348 passing (14s)
  9 pending

pure virtual method called
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock:
./run_tests.sh: line 133:   157 Aborted                 (core dumped) mocha -u tdd -t 5000 ${TESTS}
# Stats
[...]
make: *** [test-acceptance] Error 134
The command '/bin/sh -c service postgresql start && cd /Windshaft-cartodb   && make test-acceptance' returned a non-zero code: 2
```

**Comment by dgaubert** [comment]
Tests passed, but seems there is something weird. Boost is used in Mapnik, did you installed Mapnik from source? Maybe a wrong version of GCC or Boost library are causing it. I think the recommended way to install Mapnik is through [mapnik-packaging](https://github.com/mapnik/mapnik-packaging)

**Comment by pnorman** [comment]
windshaft-cartodb requires windshaft, which requires node-mapnik from https://github.com/CartoDB/node-mapnik/tarball/1.4.15-cdb6.

This in turn pulls mapnik from https://cartodb-node-binary.s3.amazonaws.com/dist/dev, which I believe is built from https://github.com/CartoDB/mapnik/tree/2.3.x.cartodb.

mapnik-packaging is for OS packaging on OS X and Windows, so it's not something you'd use when building from source normally.

**Comment by dgaubert** [comment]
Closing, due to it's a setup issue.
