### ISSUE TITLE
Range filter is not working on date columns

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#419]
**Steps to reproduce:**

- Open the new editor.
- Add a Time series widget to an existing map.
- Select a range in the Time series widget.

**Expected behaviour:**

- Request to Maps API succeeds and features are filtered.

**Actual behaviour:**

- The following request to the Maps API is triggered:

```
{
    "layers": [
        {
            "type": "torque",
            "options": {
                "cartocss": "/** torque visualization */\n\nMap {\n-torque-frame-count:256;\n-torque-animation-duration:30;\n-torque-time-attribute:\"wadus\";\n-torque-aggregation-function:\"count(cartodb_id)\";\n-torque-resolution:2;\n-torque-data-aggregation:linear;\n}\
n\n#arboles{\n  comp-op: lighter;\n  marker-fill-opacity: 0.9;\n  marker-line-color: #FFF;\n  marker-line-width: 0;\n  marker-line-opacity: 1;\n  marker-type: ellipse;\n  marker-width: 6;\n  marker-fill: #0F3B82;\n}\n#arboles[frame-offset=1] {\n marker-width:8;\n marker-f
ill-opacity:0.45; \n}\n#arboles[frame-offset=2] {\n marker-width:10;\n marker-fill-opacity:0.225; \n}",
                "cartocss_version": "2.1.1",
                "interactivity": [],
                "source": {
                    "id": "a45cc194-515c-493b-8392-19f39914013b"
                },
                "sql": "SELECT ST_Transform(the_geom, 3857) the_geom_webmercator, name, description, cartodb_id, created_at, updated_at, wadus\nFROM (SELECT * FROM (select * from arboles) _cdb_range_filter WHERE wadus BETWEEN 1445286375 AND 1446768675) _cdb_analysis_query
"
            }
        }
    ],
    "dataviews": {
        "723a3ba6-26ab-4697-99de-7515ae25c79c": {
            "type": "aggregation",
            "source": {
                "id": "a45cc194-515c-493b-8392-19f39914013b"
            },
            "options": {
                "column": "name",
                "aggregation": "count",
                "aggregationColumn": "name"
            }
        },
        "a79b07f4-fac4-420f-948d-d70c684359a2": {
            "type": "histogram",
            "source": {
                "id": "a45cc194-515c-493b-8392-19f39914013b"
            },
            "options": {
                "column": "wadus",
                "bins": 256
            }
        }
    },
    "analyses": [
        {
            "id": "a45cc194-515c-493b-8392-19f39914013b",
            "type": "source",
            "params": {
                "query": "select * from arboles",
                "filters": {
                    "a79b07f4-fac4-420f-948d-d70c684359a2": {
                        "type": "range",
                        "column": "wadus",
                        "params": {
                            "min": 1445286375,
                            "max": 1446768675,
                            "column_type": "date"
                        }
                    }
                }
            }
        }
    ]
}
```
- But Windshaft-CartoDB is throwing the following error:

```
 windshaft:mapconfig filters={"dataviews":{"a79b07f4-fac4-420f-948d-d70c684359a2":{"min":1445286375,"max":1446768675,"column_type":"date"}}} +4ms
  windshaft:torque Running query select * from (SELECT ST_Transform(the_geom, 3857) the_geom_webmercator, name, description, cartodb_id, created_at, updated_at, wadus
FROM (SELECT * FROM (select * from arboles) _cdb_range_filter WHERE wadus BETWEEN 1445286375 AND 1446768675) _cdb_analysis_query) __torque_wrap_sql limit 0 with params [object Object] +5ms
  windshaft:renderercache Removing RendererCache cartodb_dev_user_8d9f4dc3-b093-497c-9d67-430b3a6e5922_db:ce02ee2fde3c5299ed6b0eae80f21c15:development_cartodb_user_8d9f4dc3-b093-497c-9d67-430b3a6e5922:json.torque:0:1 on error error: TorqueRenderer: operator does not exist
: date >= integer +4ms
  windshaft:cartodb [ANONYMOUS LAYERGROUP ERROR] -- 404: error: TorqueRenderer: operator does not exist: date >= integer, error: TorqueRenderer: operator does not exist: date >= integer
    at Connection.parseE (/home/ubuntu/www/node-windshaft/current/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:566:11)
    at Connection.parseMessage (/home/ubuntu/www/node-windshaft/current/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:395:17)
    at null.<anonymous> (/home/ubuntu/www/node-windshaft/current/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:110:18)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10) +2ms
```
- Map is not refreshed.

cc: @rochoa

**Comment by juanignaciosl** [comment]
It has also happened to me in a non Torque layer.

**Comment by rochoa** [comment]
Just to be clear: it's not about being torque/non-torque is about the column being numeric or date type.

**Comment by juanignaciosl** [comment]
My example is a date column.

**Comment by rochoa** [comment]
This was fixed at https://github.com/CartoDB/Windshaft-cartodb/pull/485, which includes camshaft 0.12.x that adds support for date filters: https://github.com/CartoDB/camshaft/releases/tag/0.12.0.
