### ISSUE TITLE
`TypeError: Cannot call method 'getQuery' of undefined` when trying to instantiate a named map

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#422]
I'm seeing an error when loading an embed.... Here's the template for it's named map:

```
{
  "template": {
    "auth": {
      "method": "open"
    },
    "version": "0.0.1",
    "name": "tpl_f208a7aa_07b9_11e6_981a_080027880ca6",
    "placeholders": {
      "layer0": {
        "type": "number",
        "default": 1
      }
    },
    "layergroup": {
      "layers": [
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png",
            "subdomains": "abcd"
          }
        },
        {
          "type": "cartodb",
          "options": {
            "layer_name": "arboles",
            "cartocss": "#points['mapnik::geometry_type'=1] {\n  marker-fill-opacity: 1;\n  marker-line-color: #FFF;\n  marker-line-width: 0.5;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 8;\n  marker-fill: #FABADA;\n  marker-allow-overlap: true;\n}\n#lines['mapnik::geometry_type'=2] {\n  line-color: #000000;\n  line-width: 2;\n  line-opacity: 1;\n}\n#polygons['mapnik::geometry_type'=3] {\n  polygon-fill: #FABADA;\n  polygon-opacity: 1;\n  line-color: #FFF;\n  line-width: 0.5;\n  line-opacity: 1;\n}",
            "cartocss_version": "2.1.1",
            "interactivity": "cartodb_id",
            "source": {
              "id": "a4"
            },
            "table_name": "\"\"."
          }
        },
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png",
            "subdomains": "abcd"
          }
        }
      ],
      "stat_tag": "f208a7aa-07b9-11e6-981a-080027880ca6",
      "analyses": [
        {
          "id": "a3",
          "type": "trade-area",
          "params": {
            "source": {
              "id": "a2",
              "type": "trade-area",
              "params": {
                "source": {
                  "id": "a1",
                  "type": "buffer",
                  "params": {
                    "source": {
                      "id": "a0",
                      "type": "source",
                      "params": {
                        "query": "SELECT * FROM arboles"
                      }
                    },
                    "radius": 300
                  }
                },
                "kind": "drive",
                "time": 300
              }
            },
            "kind": "drive",
            "time": 300
          }
        }
      ]
    },
    "view": {
      "zoom": 11,
      "center": {
        "lng": 2.1524020000000004,
        "lat": 41.4031725
      },
      "bounds": {
        "west": 2.089675,
        "south": 41.358088,
        "east": 2.215129,
        "north": 41.448257
      }
    }
  }
}
```

And here's the error I'm seeing in the output of Windshaft-CartoDB:

```
  camshaft:toposort Found 3 edges +0ms
  camshaft:toposort Found 4 unique nodes +1ms
  camshaft:toposort Visiting node=5af683d5d8a6f67e11916a31cd76632884d4064f +0ms
  camshaft:toposort Visiting node=cc00bdba460fefc9e853f6207c325b992484408e +0ms
  camshaft:toposort Visiting node=3b22d8c3b5f4b55761f675bdda158e0847adf6b3 +0ms
  camshaft:toposort Visiting node=ab9d293dd55bb45513700b93f2355b738558eaa8 +0ms
[2016-04-21 13:39:08.332] [ERROR] [default] - Uncaught exception: TypeError: Cannot call method 'getQuery' of undefined
    at /home/ubuntu/www/node-windshaft/current/lib/cartodb/models/analysis-mapconfig-adapter.js:133:58
    at Array.map (native)
    at /home/ubuntu/www/node-windshaft/current/lib/cartodb/models/analysis-mapconfig-adapter.js:130:59
    at notify (/home/ubuntu/www/node-windshaft/current/node_modules/queue-async/queue.js:46:21)
    at /home/ubuntu/www/node-windshaft/current/node_modules/queue-async/queue.js:39:16
    at analysis$finish (/home/ubuntu/www/node-windshaft/current/node_modules/camshaft/lib/analysis.js:83:20)
    at /home/ubuntu/www/node-windshaft/current/node_modules/camshaft/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/www/node-windshaft/current/node_modules/camshaft/node_modules/async/lib/async.js:1209:30
    at /home/ubuntu/www/node-windshaft/current/node_modules/camshaft/lib/analysis.js:71:28
    at /home/ubuntu/www/node-windshaft/current/node_modules/camshaft/lib/service/database.js:325:16
```

cc: @rochoa

**Comment by rochoa** [comment]
That error should be handled within camshaft 😞 .

The actual problem is that the layer is pointing to a non-existent node-id: `a4`.

**Comment by alonsogarciapablo** [comment]
Yes, you're right! Then it's probably related to CartoDB/cartodb#7202.

**Comment by alonsogarciapablo** [comment]
In any case, when this happens, the request to instantiate the map never finishes... (browser shows "pending" after several minutes)
