### ISSUE TITLE
npm install extraction failure

### ISSUE THREAD

**Issue by monteno** [CartoDB/Windshaft-cartodb#621]
Hello everybody, i'm trying to install cartoDB, and after cloning the Windshaft-cartodb repo in a Ubuntu 12.04 server and then doing an npm install, it trhrows the next error .

```
`npm ERR! tar.unpack untar error /root/tmp/npm-12-ZC3-5whT/1485375047843-0.7155055978801101/tmp.tgz
npm ERR! tar.unpack untar error /root/tmp/npm-12-ZC3-5whT/1485375047843-0.7155055978801101/tmp.tgz
npm ERR! Error: invalid tar file
npm ERR!     at Extract.Parse._startEntry (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:144:13)
npm ERR!     at Extract.Parse._process (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:125:12)
npm ERR!     at BlockStream.<anonymous> (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:46:8)
npm ERR!     at BlockStream.EventEmitter.emit (events.js:95:17)
npm ERR!     at BlockStream._emitChunk (/usr/lib/node_modules/npm/node_modules/block-stream/block-stream.js:145:10)
npm ERR!     at BlockStream.resume (/usr/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/lib/node_modules/npm/node_modules/fstream/lib/reader.js:253:34)
npm ERR!     at Entry.<anonymous> (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.EventEmitter.emit (events.js:92:17)
npm ERR!     at Entry.resume (/usr/lib/node_modules/npm/node_modules/tar/lib/entry.js:92:8)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.39-34.54.amzn1.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /tmp/Windshaft-cartodb
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! tar.unpack untar error /root/tmp/npm-12-ZC3-5whT/1485375047843-0.7155055978801101/tmp.tgz
npm ERR! tar.unpack untar error /root/tmp/npm-12-ZC3-5whT/1485375047843-0.7155055978801101/tmp.tgz
npm ERR! tar.unpack untar error /root/tmp/npm-12-ZC3-5whT/1485375047843-0.7155055978801101/tmp.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/Windshaft-cartodb/npm-debug.log
npm ERR! not ok code 0`

```
I've even tried installing it inside a Docker container and still getting the same error.
Any help will be appreciated.

Thanks in advance

**Comment by christianurich** [comment]
This seems to happen after 2.87.3.

If you checkout 2.87.3 it works fine

**Comment by rochoa** [comment]
Can you share your npm-debug.log file?
