### ISSUE TITLE
Uncaught exception: TypeError: child.disconnect is not a function

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#873]
While looking into logs in production I saw:

```
Uncaught exception: TypeError: child.disconnect is not a function
    at Object.destroy (/home/ubuntu/www/node-windshaft/releases/20180213082156/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder.js:19:23)
    at Object.me.destroy (/home/ubuntu/www/node-windshaft/releases/20180213082156/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:159:13)
    at Timeout.removeIdle (/home/ubuntu/www/node-windshaft/releases/20180213082156/node_modules/grainstore/node_modules/generic-pool/lib/generic-pool.js:188:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by oleurud** [comment]
I have been looking into the last day's logs, and I have not found the error
