### ISSUE TITLE
Random failures in tests

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#959]
As of late we are getting random failures in tests:

```
  52 passing (8s)
  2 pending
  2 failing
  1) user render timeout limit vector (mapnik) layergroup creation works but vector tile request fails due to render timeout:
     Uncaught Error: Invalid response status code.
     Expected: 429
     Got: 200
     Body: 9x
layer0( 
cartodb_id" val" "	 
      at validateResponseStatus (test/support/assert.js:146:20)
      at validateResponse (test/support/assert.js:179:9)
      at Server.<anonymous> (test/support/assert.js:119:27)
      at emitCloseNT (net.js:1574:8)
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
  2)  "after each" hook for "layergroup creation works but vector tile request fails due to render timeout":
      AssertionError: uncaughtException:
Error: Invalid response status code.
     Expected: 429
     Got: 200
     Body: 9x
layer0( 
cartodb_id" val" "	 
    at validateResponseStatus (test/support/assert.js:146:20)
    at validateResponse (test/support/assert.js:179:9)
    at Server.<anonymous> (test/support/assert.js:119:27)
    at emitCloseNT (net.js:1574:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
      + expected - actual
      -1
      +0
```

I think it's appearing just in the PG10 run but it requires investigation.

**Comment by oleurud** [comment]
Yes @Algunenano It appears after adding the xenial + PG10 job in Travis

Until this change, we were checking against a normal postgres 9.5 (without our custom Postgres packages). Now we are checking `precise + PG9.5` and `xenial + PG10.1`

As I added it, I want to check it

**Comment by dgaubert** [comment]
Already merged in master
